#!/bin/bash
#---------------------------
# install required modules
# for birdhouse-cam
#---------------------------

sudo apt install python3-opencv
sudo apt install python3-pip
sudo apt install python-skimage

sudo pip3 install numpy
sudo pip3 install picamera
sudo pip3 install imutils
#sudo pip3 install opencv-python
#sudo pip3 install -U scikit-image
sudo pip3 install flask
sudo pip3 install tqdm
sudo pip3 install psutil

sudo apt-get -y install rpi.gpio
sudo pip3 install adafruit-circuitpython-dht
sudo apt-get install libgpiod2
