#!/bin/bash

# update / upgrade
sudo apt-get update
sudo apt-get upgrade

# install prerequisites
sudo apt-get -y install libffi-dev
sudo apt-get -y install libssl-dev
sudo apt-get -y install python3-dev
sudo apt-get -y install python3 python3-pip
sudo pip3 install --upgrade pip

curl https://sh.rustup.rs -sSf | sh
source "$HOME/.cargo/env"

# install docker
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker ${USER}
sudo su - ${USER}
docker version

# install docker-compose
sudo pip3 install docker-compose
