#!/bin/bash
#---------------------------
# install required modules
# for birdhouse-cam
#---------------------------

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install python3.11 python3-distutils python3-pip python3-apt apt-utils
sudo apt-get -y install python3-opencv python3-skimage
sudo apt-get -y install iputils-ping
sudo apt-get -y install libgpiod2
sudo apt-get -y install ffmpeg
sudo apt-get -y install v4l-utils
sudo apt-get -y install rpi.gpio

pip3 install --upgrade pip
pip3 install -r requirements.txt
sudo pip3 install -r requirements.txt