#--------------------------------------------
# Birdhouse Server and Database
#----------------------------------------

version: "3"

services:

  birdhouse_db:
    image:  ${IMAGE_DB:-matthiasg/rpi-couchdb:latest}
    container_name: birdhouse_db
    ports:
      - "${BIRDHOUSE_DB_PORT:-5100}:5984"
    volumes:
      - ./data/couchdb:/opt/couchdb/data
      - ./config/couchdb/default.ini:/opt/couchdb/etc/default.ini
    environment:
      - 'COUCHDB_USER=birdhouse'
      - 'COUCHDB_PASSWORD=birdhouse'
    networks:
      mynet:
        ipv4_address: 192.168.201.4

  birdhouse_server:
    build: ${CONTAINER_SERVER:-./config/container_rpi/}
    container_name: birdhouse_server
    privileged: true
    volumes:
      - ./:/usr/src/app/
      - ${BIRDHOUSE_DIR_LOGGING:-./log}:/log
      - ${BIRDHOUSE_DIR_PROJECT:-/projects/prod/birdhouse-cam/}:/projects/test/birdhouse-cam/
    ports:
      - "${BIRDHOUSE_HTTP_PORT:-8000}:8000"
#    depends_on:
#      - birdhouse_db
    restart: on-failure
    networks:
      mynet:
        ipv4_address: 192.168.201.5

  birdhouse_video_stream:
    build: ${CONTAINER_VIDEO:-./config/container_video_rpi/}
    container_name: birdhouse_video
    privileged: true
    volumes:
      - ./:/usr/src/app/
      - ${BIRDHOUSE_DIR_LOGGING:-./log}:/log
      - ${BIRDHOUSE_DIR_PROJECT:-/projects/prod/birdhouse-cam/}:/projects/test/birdhouse-cam/
    ports:
      - "${BIRDHOUSE_HTTP_VIDEO:-8008}:8008"
#    depends_on:
#      - birdhouse_db
    restart: on-failure
    networks:
      mynet:
        ipv4_address: 192.168.201.6

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.201.0/24
       

