#--------------------------------------------
# Birdhouse Server and Database
#----------------------------------------

version: "3"

services:

  birdhouse_app:
    image: httpd:latest
    container_name: birdhouse_app
    ports:
    - '${BIRDHOUSE_HTTP_PORT}:80'
    - '8081:81'
    volumes:
    - ./config/apache/apache2.conf:/usr/local/apache2/conf/apache2.conf
    - ./config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./app:/usr/local/apache2/htdocs
    - ./data/images:/usr/local/apache2/htdocs/images
    - ./data/videos:/usr/local/apache2/htdocs/videos

  birdhouse_db:
    image:  ${IMAGE_DB:-matthiasg/rpi-couchdb:latest}
    container_name: birdhouse_db
    ports:
      - "${COUCHDB_PORT}:5984"
    volumes:
      - ./data/couchdb:/opt/couchdb/data
      - ./config/couchdb/default.ini:/opt/couchdb/etc/default.ini
    environment:
      - 'COUCHDB_USER=${COUCHDB_USER}'
      - 'COUCHDB_PASSWORD=${COUCHDB_PASSWORD}'
    restart: always
    networks:
      my-net:
        ipv4_address: 192.168.202.3

  birdhouse_server:
    build: ${CONTAINER_SERVER:-./config/container_rpi/}
    container_name: birdhouse_server
    privileged: true
    volumes:
      - ${BIRDHOUSE_DIR_LOGGING:-./log}:/log
      - ${BIRDHOUSE_DIR_PROJECT:-/projects/prod/birdhouse-cam/}:/projects/test/birdhouse-cam/
      - ./:/usr/src/app/
    ports:
      - "${BIRDHOUSE_API_PORT}:${BIRDHOUSE_API_PORT}"
    depends_on:
      - birdhouse_db
    restart: always
    networks:
      my-net:
        ipv4_address: 192.168.202.4

  birdhouse_video_stream:
    build: ${CONTAINER_VIDEO:-./config/container_video_rpi/}
    container_name: birdhouse_video
    volumes:
      - ${BIRDHOUSE_DIR_LOGGING:-./log}:/log
      - ${BIRDHOUSE_DIR_PROJECT:-/projects/prod/birdhouse-cam/}:/projects/test/birdhouse-cam/
      - ./:/usr/src/app/
    ports:
      - "${BIRDHOUSE_VIDEO_PORT}:${BIRDHOUSE_VIDEO_PORT}"
#    depends_on:
#      - birdhouse_db
    restart: on-failure
    networks:
      my-net:
        ipv4_address: 192.168.202.5

networks:
  my-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.202.0/24

