#!/usr/bin/bash

source .env

LOGFILE="$BIRDHOUSE_DIR_LOGGING/server.log"
PARAM=$1

BLACK='\x1b[90m'
RED='\x1b[91m'
GREEN='\x1b[92m'
YELLOW='\x1b[93m'
BLUE='\x1b[94m'
MAGENTA='\x1b[95m'
CYAN='\x1b[96m'
WHITE='\x1b[97m'
NC='\x1b[0m' # No Color


# watch -n 1 "tail -n 20 logfile.txt | grep --color=always -E 'ERROR|WARNING' | sed 's/ERROR/\o033[1;31m&\o033[0m/g' | sed 's/WARNING/\o033[1;33m&\o033[0m/g'"

# Function to monitor logfile
monitor_logfile() {
    date
    echo
    tail -n 60 $LOGFILE | sed -e "s/\(INFO\)/$GREEN&$NC/g" -e "s/\(WARNING\)/$YELLOW&$NC/g" -e "s/\(ERROR\|CRITICAL\)/$RED&$NC/g" -e "s/\(OK\)/$MAGENTA&$NC/g" -e "s/\(DEBUG\)/$BLUE&$CYAN/g" -e "s/\(\)/$NC&/"
}

loop_logfile() {
  while true; do
    clear  # Clear the screen before each update
    monitor_logfile  # Call the function to monitor the logfile
    sleep 1  # Adjust the refresh interval as needed
  done
}

if [ ! $PARAM ]; then
  loop_logfile
  #watch "head -n 2 $LOGFILE | tail -n 60 $LOGFILE"
  #watch -n 2 "tail -n 60 $LOGFILE | grep --color=always -E 'ERROR|WARNING' | sed 's/ERROR/\o033[1;31m&\o033[0m/g' | sed 's/WARNING/\o033[1;33m&\o033[0m/g'"
  cat $LOGFILE

else
  watch "head -n 2 $LOGFILE | tail -n 120 $LOGFILE | grep $PARAM"
  cat $LOGFILE | grep $PARAM

fi
