#!/usr/bin/bash

source .env

LOGFILE="$BIRDHOUSE_DIR_LOGGING/server.log"
PARAM=$1

if [ ! $PARAM ]; then
  watch "head -n 2 $LOGFILE | tail -n 60 $LOGFILE"
  cat $LOGFILE

else
  watch "head -n 2 $LOGFILE | tail -n 120 $LOGFILE | grep $PARAM"
  cat $LOGFILE | grep $PARAM

fi
