#!/bin/bash
#---------------------------
# install required modules
# for birdhouse-cam
#---------------------------

pip3 install numpy
pip3 install picamera
pip3 install imutils
pip3 install opencv-python
pip3 install -U scikit-image
pip3 install flask

sudo apt-get -y install rpi.gpio
