#!/bin/bash

git clone --depth 1 https://code.videolan.org/videolan/x264
cd x264
./configure --host=arm-unknown-linux-gnueabi --enable-static --disable-opencl
sudo make install

cd ..

git clone git://source.ffmpeg.org/ffmpeg --depth=1
cd ffmpeg
/configure --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
make -j4
sudo make install
