//--------------------------------------
// jc://app-framework/, (c) Christoph Kloth
//--------------------------------------
// multi-language support (implementation just started)
//--------------------------------------
// language_app[LANG][<param>]
// add your app specific translations

var language_app = {
	"DE" : {
	    "ANALYTICS"             : "Analyse",
		"APP_TRANSLATION"       : "App spezifische Übersetzungen",
		"ARCHIVE"               : "Archiv",
		"CAMERA"                : "Kamera",
		"CAMERAS"               : "Kameras",
		"CAMERA_INACTIVE"       : "Kamera aktuell nicht in Betrieb.",
		"CREATE_DAY"            : "Video vom Tag erzeugen",
		"CREATE_DAY_DONE"       : "Video vom Tag erzeugt.",
		"CREATE_DAY_ERROR"      : "Fehler beim Erzeugen des Videos.",
		"CREATE_DAY_STARTED"    : "Erstellung eines Video vom Tag gestartet.",
		"DELETE_SURE"           : "Sollen wirklich alle Dateien gel&ouml;scht werden?",
		"DELETE_DONE"           : "Dateien wurden gel&ouml;scht.",
		"DEVICES"               : "Ger&auml;te",
		"DONE"                  : "Erledigt.",
		"FAVORITES"             : "Favoriten",
		"FILES"                 : "Dateien",
		"FRAMERATE"             : "Bildrate",
		"FRAME_COUNT"           : "Bildanzahl",
		"IMAGESIZE"             : "Bildgr&ouml;&szlig;e",
		"INDEX"                 : "Startseite",
		"INITIAL_SETUP"         : "<b>Erster Start:</b><br/>&nbsp;<br/>Bitte Einstellungen pr&uuml;fen und speichern, anschlie&szlig;end die Einstellungen für 'Geräte' vornehmen.",
		"LENGTH"                : "L&auml;nge",
		"NO_ENTRIES"            : "Keine Eintr&auml;ge vorhanden",
		"NO_CAMERAS"            : "Keine Kamaras verf&uuml;gbar.",
		"PLEASE_WAIT"           : "Bitte warten.",
		"RANGE_ADD_ENTRY"       : "Bitte weiteres Bild ausw&auml;hlen, um alle Bilder zwischen der Auswahl zu recyceln.",
		"RANGE_SELECTED"        : "Button dr&uuml;cken, um alle Bilder zwischen der Auswahl zu recyceln:",
		"RANGE_DELETE"          : "recycle",
		"RANGE_DONE"            : "Recycling der ausgew&auml;hlten Bilder erledigt.",
		"RECONNECT_CAMERA"      : "Kamera neu starten",
		"RECYCLE"               : "Recycle",
		"RECYCLE_DELETE"        : "Alle f&uuml;rs Recycling markierten Dateien l&ouml;schen.",
		"SAVE"                  : "Speichern",
		"SHORTEN_VIDEO"         : "Video k&uuml;rzen",
		"SHORT_VERSION"         : "Gek&uuml;rzte Version",
		"TEMPERATURE"           : "Temperatur",
		"TODAY_COMPLETE"        : "Alle von heute",
		"TRIM_DONE"             : "Gek&uuml;rztes Video wurde erzeugt.",
		"TRIM_STARTED"          : "Erzeugung des kurzen Videos wurde gestartet.",
		"VIDEOS"                : "Videos",
		"WEATHER"               : "Wetter"
		},
	"EN" : {
	    "ANALYTICS"             : "Analytics",
		"APP_TRANSLATION"       : "App specific Translations",
		"ARCHIVE"               : "Archive",
		"CAMERA"                : "Camera",
		"CAMERAS"               : "Cameras",
		"CAMERA_INACTIVE"       : "Camera not available at the moment.",
		"CREATE_DAY"            : "Create video from the day",
		"CREATE_DAY_DONE"       : "Created video from the day.",
		"CREATE_DAY_ERROR"      : "Error while creating the video.",
		"CREATE_DAY_STARTED"    : "Started to create a video of the day.",
		"DELETE_SURE"           : "Do you want to delete all files?",
		"DELETE_DONE"           : "Files deleted.",
		"DEVICES"               : "Devices",
        "DONE"                  : "Done.",
		"FAVORITES"             : "Favorites",
		"FILES"                 : "Files",
		"FRAMERATE"             : "Frame rate",
		"FRAME_COUNT"           : "Frame count",
		"IMAGESIZE"             : "Image size",
		"INDEX"                 : "Index",
		"INITIAL_SETUP"         : "<b>First Start:</b>&nbsp;<br/><br/>Please check and save settings. Then proceed with device settings.",
		"LENGTH"                : "Length",
		"NO_ENTRIES"            : "No entries available",
		"NO_CAMERAS"            : "No cameras available",
		"PLEASE_WAIT"           : "Please wait.",
		"RANGE_ADD_ENTRY"       : "Select one additional image to recycle a all image between both selected images.",
		"RANGE_SELECTED"        : "Press button to recycle all images between the selected images:",
		"RANGE_DELETE"          : "recycle",
		"RANGE_DONE"            : "Recycled selected images.",
		"RECONNECT_CAMERA"      : "Reconnect Camera",
		"RECYCLE"               : "Recycle",
		"RECYCLE_DELETE"        : "Recycle all files that are marked for deletion.",
		"SAVE"                  : "Save",
		"SHORTEN_VIDEO"         : "Shorten video",
		"SHORT_VERSION"         : "Short version",
		"TEMPERATURE"           : "Temperature",
		"TODAY_COMPLETE"        : "Today complete",
		"TRIM_DONE"             : "Created short video.",
		"TRIM_STARTED"          : "Started creation of short video.",
		"VIDEOS"                : "Videos",
		"WEATHER"               : "Weather"
		}
	}

