//--------------------------------------
// jc://app-framework/, (c) Christoph Kloth
//--------------------------------------
// multi-language support (implementation just started)
//--------------------------------------
// language_app[LANG][<param>]
// add your app specific translations

var language_app = {
	"DE" : {
	    "ACTIVITY"              : "Aktivit&auml;t",
	    "ANALYTICS"             : "Analyse",
		"APP_TRANSLATION"       : "App spezifische Übersetzungen",
		"ARCHIVE"               : "Archiv",
		"CAMERA"                : "Kamera",
		"CAMERAS"               : "Kameras",
		"CAMERA_INACTIVE"       : "Kamera aktuell nicht in Betrieb.",
		"CREATE_DAY"            : "Video vom Tag erzeugen",
		"CREATE_DAY_DONE"       : "Video vom Tag erzeugt.",
		"CREATE_DAY_ERROR"      : "Fehler beim Erzeugen des Videos.",
		"CREATE_DAY_STARTED"    : "Erstellung eines Video vom Tag gestartet.",
		"CONNECTION_ERROR"      : "Keine Verbindung zum Server",
		"DATA_LOADING_TRY_AGAIN": "Server l&auml;dt aktuell die Daten. Bitte sp&auml;ter erneut probieren.",
		"DATE"                  : "Datum",
		"DAYS"                  : "Tage",
		"DELETE_SURE"           : "Sollen wirklich alle Dateien gel&ouml;scht werden?",
		"DELETE_DONE"           : "Dateien wurden gel&ouml;scht.",
		"DELETE_REQUESTED"      : "L&ouml;schen der Dateien gestartet, bitte warten.",
		"DELETE_RANGE_DONE"     : "Ausgew&auml;hlte Dateien und Datens&auml;tze wurden gel&ouml;scht.",
		"DEVICES"               : "Ger&auml;te",
		"DONE"                  : "Erledigt.",
		"DONT_WAIT"             : "&Uuml;berspringen",
		"FAVORITES"             : "Favoriten",
		"FILES"                 : "Dateien",
		"FRAMERATE"             : "Bildrate",
		"FRAME_COUNT"           : "Bildanzahl",
		"FROM_TO_EVERY"         : "von <b>{0}</b> bis <b>{1}</b> alle <b>{2}</b>",
		"GPS_POSITION"          : "GPS Position",
		"GPS_LOCATION"          : "GPS Location",
		"HUMIDITY"              : "Luftfeuchtigkeit",
		"IMAGESIZE"             : "Bildgr&ouml;&szlig;e",
		"INDEX"                 : "Startseite",
		"INITIAL_SETUP"         : "<b>Erster Start:</b><br/>&nbsp;<br/>Bitte Einstellungen pr&uuml;fen und speichern, anschlie&szlig;end die Einstellungen für 'Geräte' vornehmen.",
		"LENGTH"                : "L&auml;nge",
		"LOCATION"              : "Ort",
		"LOGIN"                 : "Login",
		"NO_ENTRIES"            : "Keine Eintr&auml;ge vorhanden",
		"NO_CAMERAS"            : "Keine Kamaras verf&uuml;gbar.",
		"NO_IMAGE_IN_ARCHIV"    : "Kein Bild f&uuml;r diese Datum und diese Kamera",
		"NO_WEATHER_CHANGE_SETTINGS" : "Das Wetter aus dem Internet ist deaktiviert. Über die Einstellungen kann es aktiviert werden.",
		"PLEASE_WAIT"           : "Bitte warten.",
		"PRESSURE"              : "Luftdruck",
		"RANGE_ADD_ENTRY"       : "Bitte weiteres Bild ausw&auml;hlen, um alle Bilder zwischen der Auswahl zu recyceln.",
		"RANGE_SELECTED"        : "Button dr&uuml;cken, um alle Bilder zwischen der Auswahl zu recyceln:",
		"RANGE_DELETE"          : "recycle",
		"RANGE_DONE"            : "Recycling der ausgew&auml;hlten Bilder erledigt.",
		"RECONNECT_CAMERA"      : "Kamera neu starten",
		"RECORDING_TIMES"       : "Aufnahmezeiten",
		"RECYCLE"               : "Recycle",
		"RECYCLE_DELETE"        : "Alle f&uuml;rs Recycling markierten Dateien l&ouml;schen.",
		"SAVE"                  : "Speichern",
		"SHORTEN_VIDEO"         : "Video k&uuml;rzen",
		"SHORT_VERSION"         : "Gek&uuml;rzte Version",
		"SHOW"                  : "Anzeigen",
		"SOURCE"                : "Quelle",
		"STATUS"                : "Status",
		"SUNRISE"               : "Sonnenaufgang",
		"SUNSET"                : "Sonnenuntergang",
		"TEMPERATURE"           : "Temperatur",
		"TODAY_COMPLETE"        : "Alle von heute",
		"TRIM_DONE"             : "Gek&uuml;rztes Video wurde erzeugt.",
		"TRIM_STARTED"          : "Erzeugung des kurzen Videos wurde gestartet.",
		"UV_INDEX"              : "UV Index",
		"VIDEOS"                : "Videos",
		"VIDEO"                 : "Video",
		"WEATHER"               : "Wetter",
		"WEATHER_DATA_ERROR"    : "Fehlerhafte Wetterdaten.",
        "WEATHER_0"             : "klarer Himmel",
        "WEATHER_1"             : "klar",
        "WEATHER_2"             : "leicht bew&ouml;lkt",
        "WEATHER_3"             : "bedeckt",
        "WEATHER_45"            : "neblig",
        "WEATHER_48"            : "Ablagerung von Reifnebel",
        "WEATHER_51"            : "leichter Nieselregen",
        "WEATHER_53"            : "m&auml;&szlig;iger Nieselregen",
        "WEATHER_55"            : "dichter, intensiver Nieselregen",
        "WEATHER_56"            : "leichter gefrierender Nieselregen",
        "WEATHER_57"            : "dichter, intensiver gefrierender Nieselregen",
        "WEATHER_61"            : "leichter Regen",
        "WEATHER_63"            : "m&auml;&szlig;iger Regen",
        "WEATHER_65"            : "starker Regen",
        "WEATHER_66"            : "leichter gefrierender Regen",
        "WEATHER_67"            : "starker gefrierender Regen",
        "WEATHER_71"            : "leichter Schneefall",
        "WEATHER_73"            : "m&auml;&szlig;iger Schneefall",
        "WEATHER_75"            : "starker Schneefall",
        "WEATHER_77"            : "Hagel",
        "WEATHER_80"            : "leichte Regenschauer",
        "WEATHER_81"            : "m&auml;&szlig;ige Regenschauer",
        "WEATHER_82"            : "kr&auml;ftige Regenschauer",
        "WEATHER_85"            : "leichte Schneeschauer",
        "WEATHER_86"            : "schwere Schneeschauer",
        "WEATHER_95"            : "leichte oder &auml;&szlig;ige Gewitter",
        "WEATHER_96"            : "Gewitter mit leichtem Hagel",
        "WEATHER_99"            : "Gewitter mit schwerem Hagel",
		"WIND"                  : "Wind"
		},

	"EN" : {
	    "ACTIVITY"              : "Activity",
	    "ANALYTICS"             : "Analytics",
		"APP_TRANSLATION"       : "App specific Translations",
		"ARCHIVE"               : "Archive",
		"CAMERA"                : "Camera",
		"CAMERAS"               : "Cameras",
		"CAMERA_INACTIVE"       : "Camera not available at the moment.",
		"CREATE_DAY"            : "Create video from the day",
		"CREATE_DAY_DONE"       : "Created video from the day.",
		"CREATE_DAY_ERROR"      : "Error while creating the video.",
		"CREATE_DAY_STARTED"    : "Started to create a video of the day.",
		"CONNECTION_ERROR"      : "No connection to the server",
		"DATA_LOADING_TRY_AGAIN": "Server loads data at the moment. Try again later.",
		"DATE"                  : "Date",
		"DAYS"                  : "days",
		"DELETE_SURE"           : "Do you want to delete all files?",
		"DELETE_DONE"           : "Files deleted.",
		"DELETE_REQUESTED"      : "Please wait, deletion of files started.",
		"DELETE_RANGE_DONE"     : "Selected files and data have been deleted.",
		"DEVICES"               : "Devices",
        "DONE"                  : "Done.",
		"DONT_WAIT"             : "Dont wait",
		"FAVORITES"             : "Favorites",
		"FILES"                 : "Files",
		"FRAMERATE"             : "Frame rate",
		"FRAME_COUNT"           : "Frame count",
		"FROM_TO_EVERY"         : "from {1} to {2} every {3}",
		"HUMIDITY"              : "Humidity",
		"GPS_POSITION"          : "GPS Position",
		"GPS_LOCATION"          : "GPS Location",
		"IMAGESIZE"             : "Image size",
		"INDEX"                 : "Index",
		"INITIAL_SETUP"         : "<b>First Start:</b>&nbsp;<br/><br/>Please check and save settings. Then proceed with device settings.",
		"LENGTH"                : "Length",
		"LOCATION"              : "Location",
		"LOGIN"                 : "Login",
		"NO_ENTRIES"            : "No entries available",
		"NO_CAMERAS"            : "No cameras available",
		"NO_IMAGE_IN_ARCHIV"    : "Empty for this date and camera",
		"NO_WEATHER_CHANGE_SETTINGS" : "Weather from internet not activated, you can activate the weather in the settings.",
		"PLEASE_WAIT"           : "Please wait.",
		"PRESSURE"              : "Pressure",
		"RANGE_ADD_ENTRY"       : "Select one additional image to recycle a all image between both selected images.",
		"RANGE_SELECTED"        : "Press button to recycle all images between the selected images:",
		"RANGE_DELETE"          : "recycle",
		"RANGE_DONE"            : "Recycled selected images.",
		"RECONNECT_CAMERA"      : "Reconnect Camera",
		"RECORDING_TIMES"       : "Recording times",
		"RECYCLE"               : "Recycle",
		"RECYCLE_DELETE"        : "Recycle all files that are marked for deletion.",
		"SAVE"                  : "Save",
		"SHORTEN_VIDEO"         : "Shorten video",
		"SHORT_VERSION"         : "Short version",
		"SHOW"                  : "Show",
		"SOURCE"                : "Source",
		"STATUS"                : "Status",
		"SUNSET"                : "Sunset",
		"SUNRISE"               : "Sunrise",
		"TEMPERATURE"           : "Temperature",
		"TODAY_COMPLETE"        : "Today complete",
		"TRIM_DONE"             : "Created short video.",
		"TRIM_STARTED"          : "Started creation of short video.",
		"UV_INDEX"              : "UV Index",
		"VIDEOS"                : "Videos",
		"VIDEO"                 : "Video",
		"WEATHER"               : "Weather",
		"WEATHER_DATA_ERROR"    : "Errors in weather data.",
        "WEATHER_0"             : "clear sky",
        "WEATHER_1"             : "clear",
        "WEATHER_2"             : "partly cloudy",
        "WEATHER_3"             : "overcast",
        "WEATHER_45"            : "fog",
        "WEATHER_48"            : "depositing rime fog",
        "WEATHER_51"            : "light drizzle",
        "WEATHER_53"            : "moderate drizzle",
        "WEATHER_55"            : "dense intensity drizzle",
        "WEATHER_56"            : "light freezing drizzle",
        "WEATHER_57"            : "dense intensity freezing drizzle",
        "WEATHER_61"            : "slight rain",
        "WEATHER_63"            : "moderate rain",
        "WEATHER_65"            : "heavy rain",
        "WEATHER_66"            : "light freezing rain",
        "WEATHER_67"            : "heavy freezing rain",
        "WEATHER_71"            : "slight snow fall",
        "WEATHER_73"            : "moderate snow fall",
        "WEATHER_75"            : "heavy snow fall",
        "WEATHER_77"            : "snow grains",
        "WEATHER_80"            : "slight rain showers",
        "WEATHER_81"            : "moderate rain showers",
        "WEATHER_82"            : "violent rain showers",
        "WEATHER_85"            : "slight snow showers",
        "WEATHER_86"            : "heavy snow showers",
        "WEATHER_95"            : "slight or moderate thunderstorms",
        "WEATHER_96"            : "thunderstorms with slight hail",
        "WEATHER_99"            : "thunderstorms with heavy hail",
		"WIND"                  : "Wind"
		}
	}

